### ISSUE TITLE
Removing newly created draft adds an empty draft to the list

### ISSUE THREAD

**Issue by alessioalex** [kahlil/tinydraft#3]
Create a draft -> remove that draft -> empty draft appears (with id++)

**Comment by kahlil** [comment]
This is only happens when you have the app open in two different tabs because of how the localstorage changes are propagated throughout the app or something.

Will have to find a solution for this at some point but it is not important at the moment.

**Comment by alessioalex** [comment]
Actually it seems that BrowserSync was the was the faulty part here, because it was trying to keep all tabs in sync and somehow bypassing the app. When running a regular file-server I couldn't replicate this issue. So no worries, just wanted you to know the culprit.

**Comment by kahlil** [comment]
Ahh that makes sense :) thanks!
