### ISSUE TITLE
ServiceWorker!

### ISSUE THREAD

**Issue by khalillechelt** [kahlil/tinydraft#9]

**Comment by khalillechelt** [comment]
@andreruffert added ServiceWorker support via upup.js. That was really quick and nice.
I am not adding AppCache support. @gr2m advised against it. So no offline capability for iOS until they implement ServiceWorkers 👍 . Staying strong 😁

**Comment by andreruffert** [comment]
@kahlil nice one!!! 💯 

Yes AppCache is deprecated and has been removed from the Web standards as far as I know...
